<?php

use App\Category;
use Carbon\Carbon;
use Illuminate\Database\Seeder;


class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $tags = array('OB_1od5miliona',
							'OB_AleksandarAntić',
							'OB_AleksandarMartinović',
							'OB_AleksandarŠapić',
							'OB_AleksandarŠešelj',
							'OB_AleksandarVučić',
							'OB_AleksandarVulin',
							'OB_AleksandraJerkov',
							'OB_AnaBrnabić',
							'OB_BalšaBožović',
							'OB_BorisTadić',
							'OB_BorkoStefanović',
							'OB_BoškoObradović',
							'OB_BrankoRužić',
							'OB_ČedomirJovanović',
							'OB_Crkva',
							'OB_DJB',
							'OB_ĐorđeVukadinović',
							'OB_DraganĐilas',
							'OB_Palma',
							'OB_DS',
							'OB_DSS',
							'OB_DušanPetrović',
							'OB_Dveri',
							'OB_GoranTrivan',
							'OB_GoranVesić',
							'OB_GordanaČomić',
							'OB_IvicaDačić',
							'OB_JadrankaJoksimović',
							'OB_JankoVeselinović',
							'OB_JS',
							'OB_Kraljevina',
							'OB_LDP',
							'OB_Levijatan',
							'OB_MajaGojković',
							'OB_MarinikaTepić',
							'OB_MarkoBastać',
							'OB_MarkoĐurić',
							'OB_mediji',
							'OB_Metla 2020',
							'OB_MilanKrkobabić',
							'OB_MilošJovanović',
							'OB_MiroslavAleksić',
							'OB_MišaVacić',
							'OB_MuamerZukurlić',
							'OB_NarodnaStranka',
							'OB_NarodnaSeljačkaStranka',
							'OB_NarodniBlok',
							'OB_NebojšaStefanović',
							'OB_NebojšaZelenović',
							'OB_NelaKuburović',
							'OB_NemanjaŠarović',
							'OB_NenadČanak',
							'OB_NenadPopović',
							'OB_NikolaJovanović',
							'OB_NikolaSelaković',
							'OB_NovaStranka',
							'OB_NVO',
							'OB_Parlament',
							'OB_PatriotskiS',
							'OB_PokretSocijalista',
							'OB_PokretZaPreokret',
							'OB_POKS ',
							'OB_PSG',
							'OB_PUPS',
							'OB_RasimLjajić',
							'OB_SandaRaškovićIvić',
							'OB_SašaRadulović',
							'OB_SDPS',
							'OB_SergejTrifunović',
							'OB_SinišaMali',
							'OB_SMS',
							'OB_SNP',
							'OB_SNS',
							'OB_SPO',
							'OB_SPS',
							'OB_Srbija21',
							'OB_SrpskaLista',
							'OB_SRS',
							'OB_SSP',
							'OB_SVM',
							'OB_SZS',
							'OB_TatjanaMacura',
							'OB_VanjaUdovičić',
							'OB_VelimirIlić',
							'OB_VjericaRadeta',
							'OB_Vlada',
							'OB_VladimirOrlić',
							'OB_VojislavŠešelj',
							'OB_Vojvođanskifront',
							'OB_VukJeremić',
							'OB_ZajednoZaSrbiju',
							'OB_Zavetnici',
							'OB_ZdravaSrbija',
							'OB_ZlatiborLončar',
							'OB_ZoranaMihajlović',
							'OB_ZoranBabić',
							'OB_ZoranĐorđević',
							'OB_ZoranLutovac',
							'OB_ZoranRadojičić',
							'OB_ZoranŽivković',
							'OB_građani',
							'OB_dr',
							'OB_BranislavNedimović',
							'OB_BratislavGašić',
							'OB_DragomirKarić',
							'OB_DušanBajatović',
							'OB_SrpskaDesnica',
							'OB_MladenŠarčević',
							'OB_institucije',
							'OB_lekari',
							'OB_nedavimobg',
							'OB_MilošVučević',
							'OB_SlavicaĐukićDejanović',
							'OB_IgorMirović',
							'OB_SašaPaunović',
							'OB_opozicija',
							'OB_GDF',
							'OB_UDS',
							'TM_infrastruktura',
							'TM_ekonomija',
							'TM_populacionap',
							'TM_socijalnap',
							'TM_zdravstvo',
							'TM_ljudska',
							'TM_EuNato',
							'TM_internac',
							'TM_regionalnap',
							'TM_ekologija',
							'TM_obrazovanje',
							'TM_naukakult',
							'TM_vojskapolicija',
							'TM_krim',
							'TM_sudstvo',
							'TM_sport',
							'TM_crkva',
							'TM_KiM',
							'TM_digital',
							'TM_mediji',
							'TM_bojkot',
							'TM_izborniuslovi',
							'TM_polnasilje',
							'TM_saobraćaj',
							'TM_poljoprivreda',
							'TM_komunalno',
							'TM_mladi',
							'TM_stari',
							'TM_budžsredstva',
							'TM_afera',
							'TM_energetika',
							'TM_lokal',
							'TM_stranački',
							'TM_biračkispisak',
							'TM_investicije',
							'TM_korona',
							'TM_migranti',
							'TM_dr',
							'TM_izbori ',
							'TM_8mart',
							'TM_zabava',
							'TM_Beograd',
							'TM_NoviSad',
							'TM_Niš',
							'TM_crnahronika',
							'TM_protest',
							'POR_obećanje',
							'POR_pohvala',
							'POR_glas',
							'POR_napad',
							'POR_najava',
							'POR_promo',
							'POR_dr',
							'AK_poseta',
							'AK_debata',
							'AK_medijskinastup',
							'AK_miting',
							'AK_koncert',
							'AK_paketi',
							'AK_krv',
							'AK_pregled',
							'AK_večera',
							'AK_pomoć',
							'AK_programi',
							'AK_dr',
							'AK_štand',
							'AK_krizništab',
							'FI_Kina',
							'FI_SiĐiPing',
							'FI_SAD',
							'FI_DonaldTramp',
							'FI_Rusija',
							'FI_VladimirPutin',
							'FI_EU',
							'FI_Euzvaničnici',
							'FI_NATO',
							'FI_Kosovo',
							'FI_ZemljeRegiona',
							'FI_UjedinjeniArapskiEmirati',
							'FI_MuhamedBinZajed',
							'FI_dr',
							'FI_Eudržave',
							'FI_Turska',
							'SENT_poz',
							'SENT_neg',
							'SENT_neut',
							'FLAG_zloupotreba',
							'FLAG_funkcioneri',
							'FLAG_mržnja',
							'FLAG_negkamp',
							'FLAG_pritisak',

						);

    public function run()
    {


        foreach ($this->tags as $tag) {

        	$prefix = explode('_', $tag);
        	$prefix = $prefix[0] . '_';

        	DB::table('tags')->insert([
	            'name' => $tag,
	            'category_id' => $this->findCategoryID($prefix),
	            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
	        ]);
        }
    }

    public function findCategoryID($prefix) {

    	return Category::where('prefix', $prefix)->first()->id;
    }
}
